-- =========================================================
-- Aviation B2B E-Commerce Platform
-- PostgreSQL Application Schema
-- =========================================================

-- =========================================================
-- 1. ACCOUNTS & ORGANIZATIONS
-- =========================================================

CREATE TABLE companies (
    company_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name VARCHAR(255) NOT NULL,
    company_type VARCHAR(30) NOT NULL,
    tax_id VARCHAR(100),
    country_code CHAR(2) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_companies_company_type
        CHECK (
            company_type IN (
                'AIRLINE',
                'MRO',
                'SUPPLIER',
                'MIXED',
                'PLATFORM'
            )
        )
);


CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    full_name VARCHAR(150) NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_users_company
        FOREIGN KEY (company_id)
        REFERENCES companies(company_id),

    CONSTRAINT chk_users_role
        CHECK (
            role IN ('BUYER', 'SUPPLIER', 'ADMIN')
        )
);


CREATE TABLE addresses (
    address_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    recipient_name VARCHAR(150) NOT NULL,
    phone VARCHAR(30) NOT NULL,
    address_line VARCHAR(500) NOT NULL,
    city VARCHAR(100) NOT NULL,
    region VARCHAR(100),
    postal_code VARCHAR(20),
    country_code CHAR(2) NOT NULL,

    CONSTRAINT fk_addresses_company
        FOREIGN KEY (company_id)
        REFERENCES companies(company_id)
);


CREATE TABLE suppliers (
    supplier_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL UNIQUE,
    store_name VARCHAR(150) NOT NULL,
    slug VARCHAR(150) NOT NULL UNIQUE,
    description TEXT,
    logo_object_key VARCHAR(1024),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_suppliers_company
        FOREIGN KEY (company_id)
        REFERENCES companies(company_id),

    CONSTRAINT chk_suppliers_status
        CHECK (
            status IN ('PENDING', 'APPROVED', 'SUSPENDED')
        )
);


-- =========================================================
-- 2. CATALOG AND STOCK
-- =========================================================

CREATE TABLE categories (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(100) NOT NULL UNIQUE,
    slug VARCHAR(150) NOT NULL UNIQUE,
    description TEXT
);


CREATE TABLE engine_models (
    engine_model_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manufacturer VARCHAR(150) NOT NULL,
    model_name VARCHAR(150) NOT NULL,
    engine_family VARCHAR(100),
    engine_type VARCHAR(50),

    CONSTRAINT uq_engine_models_manufacturer_model
        UNIQUE (manufacturer, model_name)
);


CREATE TABLE products (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL,
    product_name VARCHAR(255) NOT NULL,
    manufacturer VARCHAR(150) NOT NULL,
    part_number VARCHAR(100) NOT NULL,
    product_type VARCHAR(20) NOT NULL,
    description TEXT,
    technical_specs JSON,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_products_category
        FOREIGN KEY (category_id)
        REFERENCES categories(category_id),

    CONSTRAINT uq_products_manufacturer_part
        UNIQUE (manufacturer, part_number),

    CONSTRAINT chk_products_product_type
        CHECK (
            product_type IN ('ENGINE', 'MODULE', 'COMPONENT')
        )
);

CREATE INDEX idx_products_part_number
    ON products(part_number);


CREATE TABLE product_images (
    image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    object_key VARCHAR(1024) NOT NULL,
    alt_text VARCHAR(255),
    sort_order INT NOT NULL DEFAULT 0,

    CONSTRAINT fk_product_images_product
        FOREIGN KEY (product_id)
        REFERENCES products(product_id),

    CONSTRAINT uq_product_images_product_sort
        UNIQUE (product_id, sort_order)
);


CREATE TABLE product_engine_compatibility (
    product_id BIGINT NOT NULL,
    engine_model_id BIGINT NOT NULL,
    evidence_reference TEXT NOT NULL,
    is_demo BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT pk_product_engine_compatibility
        PRIMARY KEY (product_id, engine_model_id),

    CONSTRAINT fk_compatibility_product
        FOREIGN KEY (product_id)
        REFERENCES products(product_id),

    CONSTRAINT fk_compatibility_engine_model
        FOREIGN KEY (engine_model_id)
        REFERENCES engine_models(engine_model_id)
);

CREATE INDEX idx_compatibility_engine_model
    ON product_engine_compatibility(engine_model_id);


CREATE TABLE seller_listings (
    listing_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    seller_sku VARCHAR(100) NOT NULL,
    condition VARCHAR(20) NOT NULL,
    price DECIMAL(18,2) NOT NULL,
    stock_quantity INT NOT NULL DEFAULT 0,
    lead_time_days INT NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_seller_listings_supplier
        FOREIGN KEY (supplier_id)
        REFERENCES suppliers(supplier_id),

    CONSTRAINT fk_seller_listings_product
        FOREIGN KEY (product_id)
        REFERENCES products(product_id),

    CONSTRAINT uq_seller_listings_supplier_sku
        UNIQUE (supplier_id, seller_sku),

    CONSTRAINT chk_seller_listings_nonnegative
        CHECK (
            price >= 0
            AND stock_quantity >= 0
            AND lead_time_days >= 0
        ),

    CONSTRAINT chk_seller_listings_condition
        CHECK (
            condition IN ('NEW', 'USED', 'REFURBISHED')
        ),

    CONSTRAINT chk_seller_listings_status
        CHECK (
            status IN ('DRAFT', 'ACTIVE', 'HIDDEN')
        )
);
    -- Index không phải table và không chứa business data mới. 
    -- Nó giúp PostgreSQL tìm kiếm nhanh hơn khi backend sau này query kiểu:
    -- SELECT *
    -- FROM products
    -- WHERE part_number = '...';
CREATE INDEX idx_seller_listings_product_status_price
    ON seller_listings(product_id, status, price);


-- =========================================================
-- 3. AIRCRAFT
-- =========================================================

CREATE TABLE aircraft (
    aircraft_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    registration_number VARCHAR(50) NOT NULL UNIQUE,
    manufacturer VARCHAR(100) NOT NULL,
    model VARCHAR(100) NOT NULL,
    aircraft_type VARCHAR(100) NOT NULL,
    year INT,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_aircraft_company
        FOREIGN KEY (company_id)
        REFERENCES companies(company_id)
);

-- =========================================================
-- 4A. ENGINES AND RUL
-- =========================================================

CREATE TABLE engines (
    engine_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aircraft_id BIGINT NOT NULL,
    engine_model_id BIGINT NOT NULL,
    engine_code VARCHAR(80) NOT NULL,
    serial_number VARCHAR(100) NOT NULL,
    current_cycle BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_engines_aircraft
        FOREIGN KEY (aircraft_id)
        REFERENCES aircraft(aircraft_id),

    CONSTRAINT fk_engines_engine_model
        FOREIGN KEY (engine_model_id)
        REFERENCES engine_models(engine_model_id),

    CONSTRAINT uq_engines_aircraft_code
        UNIQUE (aircraft_id, engine_code),

    CONSTRAINT uq_engines_model_serial
        UNIQUE (engine_model_id, serial_number),

    CONSTRAINT chk_engines_current_cycle
        CHECK (current_cycle >= 0)
);


CREATE TABLE ml_model_versions (
    model_version_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_name VARCHAR(100) NOT NULL,
    version VARCHAR(80) NOT NULL,
    dataset_subset VARCHAR(30) NOT NULL,
    model_object_key VARCHAR(1024) NOT NULL,
    scaler_object_key VARCHAR(1024) NOT NULL,
    preprocessing_version VARCHAR(80) NOT NULL,
    window_size INT NOT NULL DEFAULT 30,
    sensor_schema JSON NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_ml_model_versions_name_version
        UNIQUE (model_name, version),

    CONSTRAINT chk_ml_model_versions_window_size
        CHECK (window_size > 0)
);



-- =========================================================
-- 4B. RUL PREDICTION PIPELINE
-- =========================================================

CREATE TABLE sensor_uploads (
    upload_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    engine_id BIGINT NOT NULL,
    uploaded_by BIGINT NOT NULL,
    original_file_name VARCHAR(255) NOT NULL,
    object_key VARCHAR(1024) NOT NULL,
    file_sha256 CHAR(64) NOT NULL,
    dataset_subset VARCHAR(30) NOT NULL,
    dataset_unit_id VARCHAR(80) NOT NULL,
    first_cycle BIGINT,
    last_cycle BIGINT,
    row_count INT,
    is_demo BOOLEAN NOT NULL DEFAULT TRUE,
    status VARCHAR(20) NOT NULL DEFAULT 'UPLOADED',
    validation_error TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_sensor_uploads_engine
        FOREIGN KEY (engine_id)
        REFERENCES engines(engine_id),

    CONSTRAINT fk_sensor_uploads_uploaded_by
        FOREIGN KEY (uploaded_by)
        REFERENCES users(user_id),

    CONSTRAINT chk_sensor_uploads_status
        CHECK (status IN ('UPLOADED', 'VALID', 'INVALID')),

    CONSTRAINT chk_sensor_uploads_cycle_range
        CHECK (
            first_cycle IS NULL
            OR last_cycle IS NULL
            OR last_cycle >= first_cycle
        ),

    CONSTRAINT chk_sensor_uploads_row_count
        CHECK (
            row_count IS NULL
            OR row_count > 0
        )
);

CREATE INDEX idx_sensor_uploads_engine_created
    ON sensor_uploads(engine_id, created_at);


CREATE TABLE rul_predictions (
    prediction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    upload_id BIGINT NOT NULL,
    model_version_id BIGINT NOT NULL,
    requested_by BIGINT NOT NULL,
    request_key VARCHAR(100) NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL DEFAULT 'RUNNING',
    predicted_rul DECIMAL(12,3),
    cycle_at_prediction BIGINT,
    urgency VARCHAR(20),
    decision_rule_snapshot JSON NOT NULL,
    recommendation_config_snapshot JSON,
    recommendation_status VARCHAR(20) NOT NULL DEFAULT 'NOT_RUN',
    explanation TEXT,
    error_message TEXT,
    prediction_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,

    CONSTRAINT fk_rul_predictions_upload
        FOREIGN KEY (upload_id)
        REFERENCES sensor_uploads(upload_id),

    CONSTRAINT fk_rul_predictions_model_version
        FOREIGN KEY (model_version_id)
        REFERENCES ml_model_versions(model_version_id),

    CONSTRAINT fk_rul_predictions_requested_by
        FOREIGN KEY (requested_by)
        REFERENCES users(user_id),

    CONSTRAINT chk_rul_predictions_status
        CHECK (
            status IN ('RUNNING', 'SUCCEEDED', 'FAILED')
        ),

    CONSTRAINT chk_rul_predictions_predicted_rul
        CHECK (
            predicted_rul IS NULL
            OR predicted_rul >= 0
        ),

    CONSTRAINT chk_rul_predictions_urgency
        CHECK (
            urgency IS NULL
            OR urgency IN (
                'NORMAL',
                'MONITOR',
                'PREPARE',
                'PRIORITIZE'
            )
        ),

    CONSTRAINT chk_rul_predictions_success_fields
        CHECK (
            status <> 'SUCCEEDED'
            OR (
                predicted_rul IS NOT NULL
                AND cycle_at_prediction IS NOT NULL
                AND urgency IS NOT NULL
                AND completed_at IS NOT NULL
            )
        ),

    CONSTRAINT chk_rul_predictions_recommendation_status
        CHECK (
            recommendation_status IN (
                'NOT_RUN',
                'READY',
                'NO_MATCH',
                'FAILED'
            )
        )
);

CREATE INDEX idx_rul_predictions_upload_date
    ON rul_predictions(upload_id, prediction_date);


CREATE TABLE replacement_recommendations (
    recommendation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prediction_id BIGINT NOT NULL,
    listing_id BIGINT NOT NULL,
    rank_position INT NOT NULL,
    ranking_score DECIMAL(12,6) NOT NULL,
    reason TEXT NOT NULL,
    listing_snapshot JSON NOT NULL,

    CONSTRAINT fk_replacement_recommendations_prediction
        FOREIGN KEY (prediction_id)
        REFERENCES rul_predictions(prediction_id),

    CONSTRAINT fk_replacement_recommendations_listing
        FOREIGN KEY (listing_id)
        REFERENCES seller_listings(listing_id),

    CONSTRAINT uq_recommendations_prediction_listing
        UNIQUE (prediction_id, listing_id),

    CONSTRAINT uq_recommendations_prediction_rank
        UNIQUE (prediction_id, rank_position),

    CONSTRAINT chk_recommendations_rank_position
        CHECK (rank_position > 0)
);



-- =========================================================
-- 5. SHOPPING
-- =========================================================

CREATE TABLE carts (
    cart_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_carts_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
);


CREATE TABLE cart_items (
    cart_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id BIGINT NOT NULL,
    listing_id BIGINT NOT NULL,
    quantity INT NOT NULL DEFAULT 1,

    CONSTRAINT fk_cart_items_cart
        FOREIGN KEY (cart_id)
        REFERENCES carts(cart_id),

    CONSTRAINT fk_cart_items_listing
        FOREIGN KEY (listing_id)
        REFERENCES seller_listings(listing_id),

    CONSTRAINT uq_cart_items_cart_listing
        UNIQUE (cart_id, listing_id),

    CONSTRAINT chk_cart_items_quantity
        CHECK (quantity > 0)
);


CREATE TABLE wishlist_items (
    user_id BIGINT NOT NULL,
    listing_id BIGINT NOT NULL,

    CONSTRAINT pk_wishlist_items
        PRIMARY KEY (user_id, listing_id),

    CONSTRAINT fk_wishlist_items_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id),

    CONSTRAINT fk_wishlist_items_listing
        FOREIGN KEY (listing_id)
        REFERENCES seller_listings(listing_id)
);



-- =========================================================
-- 6. ORDERS, PAYMENT AND SHIPPING
-- =========================================================

CREATE TABLE orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR(50) NOT NULL UNIQUE,
    buyer_company_id BIGINT NOT NULL,
    placed_by BIGINT NOT NULL,
    checkout_key VARCHAR(100) NOT NULL,
    purchase_reference VARCHAR(100),

    company_name_snapshot VARCHAR(255) NOT NULL,
    tax_id_snapshot VARCHAR(100),
    shipping_address_snapshot JSON NOT NULL,
    billing_address_snapshot JSON NOT NULL,

    currency CHAR(3) NOT NULL DEFAULT 'USD',
    subtotal DECIMAL(18,2) NOT NULL,
    shipping_total DECIMAL(18,2) NOT NULL DEFAULT 0,
    grand_total DECIMAL(18,2) NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_orders_buyer_company
        FOREIGN KEY (buyer_company_id)
        REFERENCES companies(company_id),

    CONSTRAINT fk_orders_placed_by
        FOREIGN KEY (placed_by)
        REFERENCES users(user_id),

    CONSTRAINT uq_orders_placed_by_checkout_key
        UNIQUE (placed_by, checkout_key),

    CONSTRAINT chk_orders_currency
        CHECK (currency = 'USD'),

    CONSTRAINT chk_orders_nonnegative_totals
        CHECK (
            subtotal >= 0
            AND shipping_total >= 0
        ),

    CONSTRAINT chk_orders_grand_total
        CHECK (
            grand_total = subtotal + shipping_total
        )
);

CREATE INDEX idx_orders_buyer_company_created
    ON orders(buyer_company_id, created_at);


CREATE TABLE seller_orders (
    seller_order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    supplier_id BIGINT NOT NULL,

    supplier_name_snapshot VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'CONFIRMED',

    subtotal DECIMAL(18,2) NOT NULL,
    shipping_fee DECIMAL(18,2) NOT NULL DEFAULT 0,
    grand_total DECIMAL(18,2) NOT NULL,

    processing_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_seller_orders_order
        FOREIGN KEY (order_id)
        REFERENCES orders(order_id),

    CONSTRAINT fk_seller_orders_supplier
        FOREIGN KEY (supplier_id)
        REFERENCES suppliers(supplier_id),

    CONSTRAINT uq_seller_orders_order_supplier
        UNIQUE (order_id, supplier_id),

    CONSTRAINT chk_seller_orders_status
        CHECK (
            status IN (
                'CONFIRMED',
                'PROCESSING',
                'SHIPPED',
                'DELIVERED'
            )
        ),

    CONSTRAINT chk_seller_orders_nonnegative_totals
        CHECK (
            subtotal >= 0
            AND shipping_fee >= 0
        ),

    CONSTRAINT chk_seller_orders_grand_total
        CHECK (
            grand_total = subtotal + shipping_fee
        )
);

CREATE INDEX idx_seller_orders_supplier_status
    ON seller_orders(supplier_id, status);


CREATE TABLE order_items (
    order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_order_id BIGINT NOT NULL,
    listing_id BIGINT NOT NULL,

    product_name_snapshot VARCHAR(255) NOT NULL,
    part_number_snapshot VARCHAR(100) NOT NULL,
    seller_sku_snapshot VARCHAR(100) NOT NULL,
    condition_snapshot VARCHAR(20) NOT NULL,

    quantity INT NOT NULL,
    unit_price DECIMAL(18,2) NOT NULL,
    line_total DECIMAL(18,2) NOT NULL,

    CONSTRAINT fk_order_items_seller_order
        FOREIGN KEY (seller_order_id)
        REFERENCES seller_orders(seller_order_id),

    CONSTRAINT fk_order_items_listing
        FOREIGN KEY (listing_id)
        REFERENCES seller_listings(listing_id),

    CONSTRAINT uq_order_items_seller_order_listing
        UNIQUE (seller_order_id, listing_id),

    CONSTRAINT chk_order_items_values
        CHECK (
            quantity > 0
            AND unit_price >= 0
        ),

    CONSTRAINT chk_order_items_line_total
        CHECK (
            line_total = quantity * unit_price
        )
);


CREATE TABLE payments (
    payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL UNIQUE,

    payment_method VARCHAR(30) NOT NULL DEFAULT 'SIMULATION',
    amount DECIMAL(18,2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'SUCCEEDED',
    paid_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_payments_order
        FOREIGN KEY (order_id)
        REFERENCES orders(order_id),

    CONSTRAINT chk_payments_amount
        CHECK (amount >= 0),

    CONSTRAINT chk_payments_simulation
        CHECK (
            payment_method = 'SIMULATION'
            AND status = 'SUCCEEDED'
        )
);


CREATE TABLE shipments (
    shipment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_order_id BIGINT NOT NULL UNIQUE,

    carrier VARCHAR(100) NOT NULL,
    tracking_number VARCHAR(150),
    shipped_at TIMESTAMP NOT NULL,
    estimated_delivery_at TIMESTAMP,
    delivered_at TIMESTAMP,

    CONSTRAINT fk_shipments_seller_order
        FOREIGN KEY (seller_order_id)
        REFERENCES seller_orders(seller_order_id),

    CONSTRAINT uq_shipments_carrier_tracking
        UNIQUE (carrier, tracking_number),

    CONSTRAINT chk_shipments_delivery_time
        CHECK (
            delivered_at IS NULL
            OR delivered_at >= shipped_at
        )
);

-- =========================================================
-- 7. REVIEWS AND NOTIFICATIONS
-- =========================================================

CREATE TABLE reviews (
    review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_item_id BIGINT NOT NULL UNIQUE,
    reviewer_user_id BIGINT NOT NULL,
    product_rating INT NOT NULL,
    supplier_rating INT NOT NULL,
    comment TEXT,
    is_visible BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_reviews_order_item
        FOREIGN KEY (order_item_id)
        REFERENCES order_items(order_item_id),

    CONSTRAINT fk_reviews_reviewer
        FOREIGN KEY (reviewer_user_id)
        REFERENCES users(user_id),

    CONSTRAINT chk_reviews_product_rating
        CHECK (product_rating BETWEEN 1 AND 5),

    CONSTRAINT chk_reviews_supplier_rating
        CHECK (supplier_rating BETWEEN 1 AND 5)
);


CREATE TABLE notifications (
    notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    action_path VARCHAR(500),
    read_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_notifications_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
);

CREATE INDEX idx_notifications_user_read_created
    ON notifications(user_id, read_at, created_at);